# AI Mega Agents Factory - Kubernetes Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-mega-agents-factory
  labels:
    app: ai-mega-agents-factory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-mega-agents-factory
  template:
    metadata:
      labels:
        app: ai-mega-agents-factory
    spec:
      containers:
      - name: agents-api
        image: ai-mega-agents-factory:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: MAX_CONCURRENT_AGENTS
          value: "100"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: ai-mega-agents-factory-service
spec:
  selector:
    app: ai-mega-agents-factory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-mega-agents-factory-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-mega-agents-factory
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agents-config
data:
  config.yaml: |
    agents:
      data_analysis:
        enabled: true
        tier_limits:
          free: 10
          basic: 100
          premium: 1000
          enterprise: -1
      email:
        enabled: true
        tier_limits:
          free: 5
          basic: 50
          premium: 500
          enterprise: -1
      document_processing:
        enabled: true
        tier_limits:
          free: 5
          basic: 50
          premium: 500
          enterprise: -1
    
    pricing:
      data_analysis:
        free: 0.0
        basic: 0.01
        premium: 0.005
        enterprise: 0.001
      email:
        free: 0.0
        basic: 0.02
        premium: 0.01
        enterprise: 0.005
      document_processing:
        free: 0.0
        basic: 0.03
        premium: 0.015
        enterprise: 0.01