# AI Mega Agents Atlas - Kubernetes Deployment

apiVersion: v1
kind: Namespace
metadata:
  name: mega-agents
  labels:
    name: mega-agents
    app: ai-mega-agents-atlas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mega-agents-api
  namespace: mega-agents
  labels:
    app: mega-agents-api
    component: api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mega-agents-api
  template:
    metadata:
      labels:
        app: mega-agents-api
        component: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: mega-agents/api-gateway:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: POSTGRES_URL
          value: "postgresql://postgres:password@postgres-service:5432/mega_agents"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mega-agents-api-service
  namespace: mega-agents
  labels:
    app: mega-agents-api
spec:
  selector:
    app: mega-agents-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-agent
  namespace: mega-agents
  labels:
    app: analytics-agent
    component: agent
    agent-type: analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-agent
  template:
    metadata:
      labels:
        app: analytics-agent
        component: agent
        agent-type: analytics
    spec:
      containers:
      - name: analytics-agent
        image: mega-agents/analytics-agent:latest
        ports:
        - containerPort: 8001
          name: agent-port
        env:
        - name: AGENT_TYPE
          value: "analytics"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: POSTGRES_URL
          value: "postgresql://postgres:password@postgres-service:5432/mega_agents"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: analytics-agent-hpa
  namespace: mega-agents
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-agent
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80